### ISSUE TITLE
Installing is a hassle

### ISSUE THREAD

**Issue by userx-bw** [aanatoly/fbpanel#28]
you got a really great panel. I love it! but your install needs major work. one system it installed with out any problems. I like your panel so much I went to install it on my other linux box, and I got nothing but errors and not allowing me to install it. So I gave up and went with something else. 

I googled around to see if I cold find a solution. Then found a post on a board of someone getting fed up with your app not installing too. Only to leave a nasty gram as a result of it. 

This was a while ago (two maybe three weeks) so I do not remember all of the errors messages. Not that it should matter. Just come up with a better way to install it is all. 

again, it is a great looking panel just put more effort in how another is to get it into their system and working.

**Comment by dave-kennedy** [comment]
I've never had any issues installing fbpanel. Without specific error messages it's hard to improve anything.

**Comment by userx-bw** [comment]
Yeah sorry bout dat, when I fire up my other sys, which is an external HDD pluged into my usb, I'll give it another spin, if it repeats what it did, then I'll shoot them over to ya. so you can have a look see. K?

**Comment by userx-bw** [comment]
using git fbpanel-master

11:56 AM ~/Downloads/fbpanel-master$ ./configure
Traceback (most recent call last):
  File "./configure", line 502, in <module>
    main()
  File "./configure", line 489, in main
    resolve()
  File ".config/options.py", line 64, in resolve
    if opt('sound') is None and pkg_exists('alsa', '--atleast-version=1.0.10'):
  File "./configure", line 297, in pkg_exists
    return sp.call(cmd) == 0
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

my system showing  alsa is installed
[*] alsa-lib-1.1.0_1                The Advanced Linux Sound Architecture

in INSTALL.md  FILE
./configure
make
su -c "make install"

```

## System Install
Build and install it
```

./configure
make
su -c "make install"

```

# Dependencies
Deps:
 * core - gtk2 2.17 or higher
 * plugin `foo` - bar 1.0

######
 Using the fbpanel6.1 tar ball
I have to specify everything before it'd even get past configure

12:05 PM ~/Downloads/fbpanel-6.1$ ./configure --glib_cflags=2.0 --gtk_cflags=2.0 --glib_libs=2.0 --gtk_libs=2.0 --gmodule_libs=2.0 
Creating ./Makefile
Creating ./data/Makefile
Creating ./data/images/Makefile
Creating ./data/man/fbpanel.1
Creating ./data/config/Makefile
Creating ./data/config/pager
Creating ./data/config/default
Creating ./exec/Makefile
Creating ./exec/make_profile
Creating ./panel/Makefile
Creating ./plugins/taskbar/Makefile
Creating ./plugins/image/Makefile
Creating ./plugins/tclock/Makefile
Creating ./plugins/unstable/test/Makefile
Creating ./plugins/pager/Makefile
Creating ./plugins/chart/Makefile
Creating ./plugins/Makefile
Creating ./plugins/volume/Makefile
Creating ./plugins/wincmd/Makefile
Creating ./plugins/mem/Makefile
Creating ./plugins/menu/Makefile
Creating ./plugins/launchbar/Makefile
Creating ./plugins/meter/Makefile
Creating ./plugins/cpu/Makefile
Creating ./plugins/space/Makefile
Creating ./plugins/battery/Makefile
Creating ./plugins/deskno2/Makefile
Creating ./plugins/deskno/Makefile
Creating ./plugins/net/Makefile
Creating ./plugins/genmon/Makefile
Creating ./plugins/systray/Makefile
Creating ./plugins/icons/Makefile
Creating ./plugins/separator/Makefile
Creating ./plugins/dclock/Makefile
Creating config.h
Creating config.mk
12:05 PM ~/Downloads/fbpanel-6.1$ make
make[1]: Entering directory '/home/mike/Downloads/fbpanel-6.1/plugins'
make[2]: Entering directory '/home/mike/Downloads/fbpanel-6.1/plugins/taskbar'
cc -O2 -Wall -I/home/mike/Downloads/fbpanel-6.1  -I/home/mike/Downloads/fbpanel-6.1/panel 2.0 2.0 -fPIC -DPLUGIN -c -o taskbar.o taskbar.c
cc: error: 2.0: No such file or directory
cc: error: 2.0: No such file or directory
/home/mike/Downloads/fbpanel-6.1/rules.mk:73: recipe for target 'taskbar.o' failed
make[2]: *** [taskbar.o] Error 1
make[2]: Leaving directory '/home/mike/Downloads/fbpanel-6.1/plugins/taskbar'
/home/mike/Downloads/fbpanel-6.1/rules.mk:14: recipe for target 'taskbar' failed
make[1]: *** [taskbar] Error 2
make[1]: Leaving directory '/home/mike/Downloads/fbpanel-6.1/plugins'
/home/mike/Downloads/fbpanel-6.1/rules.mk:14: recipe for target 'plugins' failed
make: *** [plugins] Error 2


it may not be a "bug" but it is a pain in my arse ~ especailly when my other systhem tha is the same Linux installed without error of any kind. 
```

**Comment by willbprog127** [comment]
> cc -O2 -Wall -I/home/mike/Downloads/fbpanel-6.1  -I/home/mike/Downloads/fbpanel-6.1/panel 2.0 2.0 -fPIC -DPLUGIN -c -o taskbar.o taskbar.c

You have two straggling `2.0`'s there, which appear to be the glib and gtk flags.  I'm not sure why you have to specify everything explicitly, though.  Do you have `pkg-config` installed?

**Comment by willbprog127** [comment]
@userx-bw I did a clean install and I also saw what you saw.

I had to do the following to make it work:
Add the following to the end of LDFLAGSX in `config.mk` and save:
`-lX11 -lm`

I'm not sure why those are not being added automatically, but this edit fixed it for me.

**Comment by dave-kennedy** [comment]
I was just about to say the same thing :)

I didn't notice it before because this patch is part of the Gentoo ebuild.

``` diff
--- a/scripts/custom.sh
+++ b/scripts/custom.sh
@@ -18,10 +18,10 @@
 add_feature dependency "disable dependency tracking" disabled

 add_var glib_cflags "glib cflags" '`RFS=$rfs scripts/rfs-pkg-config --cflags glib-2.0`'
-add_var gtk_cflags "gtk cflags" '`RFS=$rfs scripts/rfs-pkg-config --cflags gtk+-2.0`'
+add_var gtk_cflags "gtk cflags" '`RFS=$rfs scripts/rfs-pkg-config --cflags gtk+-2.0 x11`'

 add_var glib_libs "glib libs" '`RFS=$rfs scripts/rfs-pkg-config --libs glib-2.0`'
-add_var gtk_libs "gtk libs" '`RFS=$rfs scripts/rfs-pkg-config --libs gtk+-2.0`'
+add_var gtk_libs "gtk libs" '`RFS=$rfs scripts/rfs-pkg-config --libs gtk+-2.0 x11` -lm'

 add_var cflagsx "C flags" '-I$topdir/panel $glib_cflags $gtk_cflags -fPIC'
 add_var ldflagsx "linker flags" '$glib_libs $gtk_libs'
```

**Comment by willbprog127** [comment]
> /scripts/custom.sh

Ah!  That's where it is.  Good find! :clap:
